### PR TITLE
Update class Ingredient

### PR DESCRIPTION
**Pull request by dgubko**
Updated class Ingredients + test

### CODE REVIEW

**Review by AnnaPete — APPROVED** [review]
Looks pretty good to me

**Review by JPierce28 — CHANGES_REQUESTED** [review]
We need the ingredients class to be able to take in an array of ingredients and have methods to access each piece of information of the ingredient object.

**Review by AnnaPete — COMMENTED** [review]
Is the test supposed to be almost completely all commented out?

**Review by JPierce28 — APPROVED** [review]
Ahh that looks great Dmitrii!

**Pull request merged**
